settings:
  title: 'Status Page'
  url: 'https://status.pocketdata.io' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: backend-api # unique identifier
    name: API
    description: 'Backend services' # default=empty
    url: 'https://api.pocketdata.io/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: client-web
    name: 'Client app'
    description: 'Client web application'
    url: 'https://app.pocketdata.io/'
    method: GET
    expectStatus: 200

  - id: main
    name: Main site
    url: 'https://pocketdata.io/'
    method: GET
    expectStatus: 200
    
  - id: docs
    name: Documentation
    url: 'https://docs.pocketdata.io/'
    method: GET
    expectStatus: 200
